import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavbarDemo } from "./components/Navbar";
import { HeroScrollDemo } from "./components/Container_Scroll";
import { AnimatedPinDemo } from "./components/Card";
import { HeroParallaxDemo } from "./components/Homecover";
import { TypewriterEffectSmooth } from "./components/ui/typewriter-effect";
import { TypewriterEffectSmoothDemo } from "./components/Popular_Artist_Text";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarDemo />
        <HeroScrollDemo />
        <HeroParallaxDemo />
        <TypewriterEffectSmoothDemo />
        <AnimatedPinDemo />
        {children}
      </body>
    </html>
  );
}
